onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tarojs/binding'
  - esbuild
  - prisma
  - swiper
ignoredBuiltDependencies:
  - '@tarojs/cli'
  - core-js
  - core-js-pure
